version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    working_directory: ~/test-repo
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: root

    steps:
      - checkout #checkout source code to working directory
      - run:
          command: |
            pwd
            pip install -r requirement.txt
            python testfile.py

          name: Test

workflows:
  main:
    jobs:
      - build
